services:
  - type: web
    name: loudness-normalizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    initialDeployHook:
      # サーバー起動時にシステムへFFmpegをインストールする設定
      command: apt-get update && apt-get install -y ffmpeg
